source "https://rubygems.org"

gem "xcpretty"
gem "fastlane"
gem "dry-cli"
gem "logger"
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
