package com.emergetools.paparazzi.tasks

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import org.intellij.lang.annotations.Language
import java.io.File

@CacheableTask
abstract class GeneratePreviewScannerTestTask : DefaultTask() {

    @get:Input
    abstract val scanPackages: ListProperty<String>

    @get:Input
    abstract val namespace: Property<String>

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
      logger.lifecycle("Generating Paparazzi preview scanner test...")
        val packages = scanPackages.get().ifEmpty {
            // Default to namespace if no packages specified
            listOf(namespace.get())
        }

      logger.lifecycle("Scanning packages: $packages")
      val packageName = "com.emergetools.paparazzi.generated"
      val className = "ComposePreviewScannerTest"

        val testContent = generateTestFile(packageName, className, packages)

        // Clean output directory before generating new content
        val outputDir = outputDirectory.get().asFile
        if (outputDir.exists()) {
            logger.lifecycle("Cleaning output directory: ${outputDir.absolutePath}")
            outputDir.deleteRecursively()
        }
        val packageDir = File(outputDir, packageName.replace('.', '/'))
        packageDir.mkdirs()

        val testFile = File(packageDir, "$className.kt")
        testFile.writeText(testContent)

        logger.lifecycle("Generated Paparazzi test at: ${testFile.absolutePath}")
    }

    private fun generateTestFile(
        packageName: String,
        className: String,
        scanPackages: List<String>
    ): String {
        val packagesString = scanPackages.joinToString(", ") { "\"$it\"" }

        return """
            |package $packageName
            |
            |import app.cash.paparazzi.Paparazzi
            |import org.junit.Rule
            |import org.junit.Test
            |import org.junit.runner.RunWith
            |import org.junit.runners.Parameterized
            |import sergio.sastre.composable.preview.scanner.android.AndroidComposablePreviewScanner
            |import sergio.sastre.composable.preview.scanner.android.AndroidPreviewInfo
            |import sergio.sastre.composable.preview.scanner.android.screenshotid.AndroidPreviewScreenshotIdBuilder
            |import sergio.sastre.composable.preview.scanner.core.preview.ComposablePreview
            |
            |/**
            | * Auto-generated by Paparazzi Preview Scanner Plugin.
            | * Scans packages: ${scanPackages.joinToString(", ")}
            | */
            |@RunWith(Parameterized::class)
            |class $className(val preview: ComposablePreview<AndroidPreviewInfo>) {
            |
            |    companion object {
            |        // Optimization: This avoids scanning for every test
            |        private val cachedPreviews: List<ComposablePreview<AndroidPreviewInfo>> by lazy {
            |            AndroidComposablePreviewScanner()
            |                .scanPackageTrees($packagesString)
            |                .getPreviews()
            |        }
            |
            |        @JvmStatic
            |        @Parameterized.Parameters
            |        fun values(): List<ComposablePreview<AndroidPreviewInfo>> = cachedPreviews
            |    }
            |
            |    @get:Rule
            |    val paparazzi = Paparazzi()
            |
            |    @Test
            |    fun snapshotTest() {
            |        val screenshotId = AndroidPreviewScreenshotIdBuilder(preview).build()
            |
            |        paparazzi.snapshot(name = screenshotId) {
            |            preview()
            |        }
            |    }
            |}
            |
        """.trimMargin()
    }
}
