name: Android Release Build

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]
    paths: [ android/** ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./android

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build AAB
        env:
        run: ./gradlew :app:bundleRelease

      - name: debug
        run: find .

      - name: Convert AAB to APK
        uses: mukeshsolanki/bundletool-action@v1.0.2
        with:
          aabFile: ./app/build/outputs/bundle/release/app-release.aab
          base64Keystore: ${{ secrets.ANDROID_RELEASE_KEYSTORE_BASE64 }}
          keystoreAlias: ${{ secrets.ANDROID_RELEASE_KEY_ALIAS }}
          keyPassword: ${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}
          keystorePassword: ${{ secrets.ANDROID_RELEASE_STORE_PASSWORD }}
          bundletoolVersion: '1.9.0'

      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: ${{ steps.convert_aab.outputs.apkPath }}


