name: Sentry PR iOS Upload (Size Analysis)

on:
  pull_request:
    branches: [main]
    paths: [ios/**, .github/workflows/ios_sentry_upload_pr.yml]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ios

    steps:
      - name: Checkout PR HEAD
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Fetch base branch tip
        run: |
          git -c protocol.version=2 fetch --no-tags --prune --filter=blob:none origin \
            "+refs/heads/${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}"
          git show -s --oneline "origin/${{ github.base_ref }}"

      - name: Compute merge-base (BASE_SHA)
        shell: bash
        run: |
          set -e -o pipefail
          BASE_REF="origin/${{ github.base_ref }}"
          BASE_SHA=$(git merge-base --fork-point "$BASE_REF" HEAD 2>/dev/null)
          echo "BASE_SHA=$BASE_SHA"
