name: Sentry PR iOS Upload (Size Analysis)

on:
  pull_request:
    branches: [main]
    paths: [ios/**]

jobs:
  build:
    runs-on: macos-15

    defaults:
      run:
        working-directory: ./ios

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_16.4.app/Contents/Developer'

      - name: Set up Ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4
          bundler-cache: true

      - name: Install Sentry CLI
        run: curl -sL https://sentry.io/get-cli/ | SENTRY_CLI_VERSION="2.53.0-alpha" sh

      - name: Setup gems
        run: exec ../.github/scripts/ios/setup.sh

      - name: Decode signing certificate into a file
        env:
          CERTIFICATE_BASE64: ${{ secrets.IOS_DIST_SIGNING_KEY_BASE64 }}
        run: |
          echo $CERTIFICATE_BASE64 | base64 --decode > signing-cert.p12

      - name: Build & upload iOS size analysis binary to Emerge Tools
        run: bundle exec fastlane ios build_only
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY: ${{ secrets.ASC_PRIVATE_KEY }}
          SIGNING_KEY_PASSWORD: ${{ secrets.IOS_DIST_SIGNING_KEY_PASSWORD }}
          SIGNING_KEY_FILE_PATH: signing-cert.p12
          EMERGE_API_TOKEN: ${{ secrets.EMERGE_API_KEY }}
          CONFIGURATION: Release
          EMERGE_BUILD_TYPE: pull-request

      - name: Upload iOS size analysis binary to Sentry
        run: |
          sentry-cli \
           --log-level=debug \
           --auth-token ${{ secrets.SENTRY_SENTRY_AUTH_TOKEN }} \
           build \
           upload \
           ./build/HackerNews.xcarchive \
           --org sentry \
           --project launchpad-test-ios
