name: Emerge PR iOS Upload (Snapshots)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths: [ios/**, .github/workflows/ios*]

jobs:
  upload_emerge_snapshots:
    runs-on: macos-14

    defaults:
      run:
        working-directory: ./ios

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_15.4.app/Contents/Developer'

      - name: Set up Ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4
          bundler-cache: true

      - name: Setup gems
        run: exec ../.github/scripts/ios/setup.sh

      - name: Build & upload iOS snapshot binary to Emerge Tools
        run: bundle exec fastlane ios build_upload_emerge_snapshot
        env:
          EMERGE_API_TOKEN: ${{ secrets.EMERGE_API_KEY }}

  upload_swift_snapshot_testing_snapshots:
    runs-on: macos-14
    defaults:
      run:
        working-directory: ./ios
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_15.4.app/Contents/Developer'
      - name: Set up App Store Connect API Key
        run: |
          echo "${{ secrets.ASC_PRIVATE_KEY }}" > app_store_key.p8
          export APP_STORE_CONNECT_KEY=$(pwd)/app_store_key.p8
        env:
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.ASC_PRIVATE_KEY }}

      - name: Generate new snapshots
        env:
          APP_STORE_CONNECT_KEY: $(pwd)/app_store_key.p8
          APP_STORE_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          APP_STORE_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
        run: |
          xcodebuild test \
            -scheme HackerNews \
            -destination 'platform=iOS Simulator,name=iPhone 14' \
            -only-testing:HackerNewsTests/SwiftSnapshotTest \
            -allowProvisioningUpdates \
            -authenticationKeyPath $APP_STORE_CONNECT_KEY \
            -authenticationKeyID $APP_STORE_KEY_ID \
            -authenticationKeyIssuerID $APP_STORE_ISSUER_ID
        continue-on-error: true
      - name: Ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.5
          bundler-cache: true
      - name: Setup gems
        run: gem install emerge
      - name: Upload snapshots
        env:
          EMERGE_API_TOKEN: ${{ secrets.EMERGE_API_KEY }}
        run: |
          emerge upload snapshots \
            --name "HackerNews Swift-Snapshot-Testing" \
            --id "com.emerge.hn.Hacker-News.swiftsnapshottesting" \
            --repo-name "EmergeTools/hackernews" \
            --client-library swift-snapshot-testing \
            --project-root . \
            --debug
