name: Emerge PR iOS Upload (Snapshots)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths: [ios/**, .github/workflows/ios*]

jobs:
  build:
    runs-on: macos-14

    defaults:
      run:
        working-directory: ./ios

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_15.4.app/Contents/Developer'

      - name: Set up Ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4
          bundler-cache: true

      - name: Setup gems
        run: exec ../.github/scripts/ios/setup.sh

      - name: Build & upload iOS snapshot binary to Emerge Tools
        run: bundle exec fastlane ios build_upload_emerge_snapshot
        env:
          EMERGE_API_TOKEN: ${{ secrets.EMERGE_API_KEY }}
  upload_snapshots:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ios

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.5
          bundler-cache: true

      - name: Setup gems
        run: gem install emerge

      - name: Upload snapshots
        env:
          EMERGE_API_TOKEN: ${{ secrets.EMERGE_API_KEY }}
        run: |
          emerge upload snapshots \
            --name "HackerNews Swift-Snapshot-Testing" \
            --id "com.emerge.hn.Hacker-News.swiftsnapshottesting" \
            --repo-name "EmergeTools/hackernews" \
            --client-library swift-snapshot-testing \
            --project-root . \
            --debug
