name: Sentry PR iOS Upload (Size Analysis)

on:
  pull_request:
    branches: [main]
    paths: [ios/**, .github/workflows/ios_sentry_upload_pr.yml]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ios

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: test
        run: echo $(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
